
<!DOCTYPE HTML>

<head>
  <meta charset="utf-8" />
    <title>Portfolio - Van Autrui</title>
    <link rel="stylesheet" type="text/css" href="style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>

<body>

  <?php
    include("logo_fragment.php");
  ?>


  <!-- https://www.datenschutz.org/website/ -->
  <div id="Portfolio" class="container">
        <div class="m-3"></div>
        <h1 class="display-4 text-center"> Projects we completed </h1>
        <div class="m-3"></div>
        <div class="row">
            <div class="col">
                <div class="card border-info mb-3">
                    <div class="card-header text-center">
                        <a href="https://github.com/RayNCooper/ProvinzialWohnen"> <h3>Team Procoli - Geschaeftsidee fuer eine neue Art, zu wohnen</h3></a>
                    </div>
                    <div class="card-body text-center">
                        <div class="card-title">
                            Dieses Projekt ist beim Provinzial Hackathon 2018 in Duesseldorf entstanden,
                            in Zusammenarbeit mit <a href="https://reinkober-it.de/"> Dennis </a> und einigen anderen.
                        </div>
                    </div>
                    <div class="card-footer text-center">
                    <span class="badge badge-pill badge-dark">Leaflet.js</span>
                    <span class="badge badge-pill badge-dark">OpenStreetMap</span>
                        <span class="badge badge-pill badge-dark">Hackathon Project</span>
                    </div>
                </div>

                <div class="card  border-info mb-3">
                    <div class="card-header text-center">
                        <a href="https://github.com/pointbazaar/Kreta"><h3> Team Kreta - Programming for the Mycroft Voice Assistant Platform</h3></a>
                    </div>
                    <div class="card-body">
                        <div class="card-title text-center">
                            Dieses Projekt ist beim Kreathon 2018 in Krefeld entstanden,
                            in Zusammenarbeit mit <a href="https://reinkober-it.de/"> Dennis </a> und einigen anderen.
                        </div>
                    </div>
                    <div class="card-footer text-center">
                        <span class="badge badge-pill badge-dark">Python</span>
                        <span class="badge badge-pill badge-dark">Mycroft</span>
                        <span class="badge badge-pill badge-dark">Hackathon Project</span>
                    </div>
                </div>
                <div class="card border-info mb-3">
                    <div class="card-header text-center">
                        <a href="https://www.freelancer.com/projects/website-design/Convert-Web-Page-from-WIX-18324835/?w=f#"> <h3>Website change  from Wix website to a static website</h3></a>
                    </div>
                    <div class="card-body text-center">
                        <div class="card-title">
                            The task was to recreate <a href="https://www.takeheed.org/">takeheed.org</a> in HTML,CSS and Javascript.
                            The problem was, the HTML was generated by wix.

                        </div>

                        <p>What the client said: <br>
                        <blockquote>
                            <p>
                          "I'm incredibly impressed, he may be new to the game, but he's learning fast!<br>
                          Grasped the idea without needing hand-holding. <br>
                          Developed his own solutions to problems rather than pushing back on the whole project.<br>
                          Delivered on-time, fully fleshed out and at a great price!"
                      </p>
                        </blockquote>
                        </p>
                    </div>
                    <div class="card-footer text-center">
                        <span class="badge badge-pill badge-dark">Bootstrap</span>
                        <span class="badge badge-pill badge-dark">Wix</span>
                        <span class="badge badge-pill badge-dark">freelancer.com Project</span>
                    </div>
                </div>
            </div>
        </div>
  </div>

  <div id="footer"></div>
  <?php
    include("footer.html");
  ?>
</body>
</html>
