
<!DOCTYPE HTML>

<head>
  <meta charset="utf-8" />
    <title>Portfolio - Van Autrui</title>
    <link rel="stylesheet" type="text/css" href="style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>

<body>

  <?php
    include("logo_fragment.php");
  ?>


  <!-- https://www.datenschutz.org/website/ -->
  <div id="Portfolio" class="container-fluid">
        <div class="m-3"></div>
        <h1 class="display-4 text-center"> Projects we completed </h1>
        <div class="m-3"></div>
        <div class="row justify-content-center">

            <?php
                $project_titles=array(
                    "Website conversion from Wix Site to static Website",
                    "In Progress - Ticket Shop and Website for Event Promoter"
                );

                $project_title_links=array(
                    "https://www.freelancer.com/projects/website-design/Convert-Web-Page-from-WIX-18324835/?w=f#",
                    "https://afropeanbase.com"
                );

                $project_tags = array(
                        array("Bootstrap","freelancer.com Project"),
                        array("Wordpress","Woocommerce","Email","Ecommerce","QR Codes","Java")
                );

                $project_htmls = array(

                        "The task was to recreate <a href=\"https://www.takeheed.org/\">takeheed.org</a> in HTML,CSS and Javascript.<br>
                        The problem was, the HTML was generated by wix.
                            <p>What the client said: <br>
                            <blockquote>
                                <p>
                              \"I'm incredibly impressed, <br>
                                he may be new to the game, but he's learning fast!<br>
                              Grasped the idea without needing hand-holding. <br>
                              Developed his own solutions to problems <br>
                                rather than pushing back on the whole project.<br>
                              Delivered on-time, fully fleshed out and at a great price!\"
                          </p>
                            </blockquote>
                            </p>",
                        "<p>The task was to create a ticket shop and website for an Event Promoter.</p><a href='https://afropeanbase.com'>afropeanbase.com</a>"
                    );

                for($i=0;$i<sizeof($project_titles);$i++) {
                    echo "<div class='card border-info mb-3 m-3'>";

                        //card header

                        echo "<div class='card-header text-center'>";
                            echo "<a href='" . $project_title_links[$i] . "'>";
                                echo "<h3>" . $project_titles[$i] . "</h3>";
                            echo "</a>";
                        echo "</div>";

                        //card body

                        echo "<div class='card-body text-center'>";
                            echo "<div class='card-text'>";
                                echo $project_htmls[$i];
                            echo "</div>";
                        echo "</div>";


                        //card footer

                        echo "<div class='card-footer text-center'>";
                            for($j=0;$j<sizeof($project_tags[$i]);$j++){
                                echo "<span class='badge badge-pill badge-dark m-2'>";
                                    echo $project_tags[$i][$j];
                                echo "</span>";
                            }
                        echo "</div>";

                    echo "</div>";
                }


            ?>

        </div>

  </div>

  <div id="footer"></div>
  <?php
    include("footer.html");
  ?>
</body>
</html>
